events {}

http {
    upstream servidores {
        server servidor1:8000;
        server servidor2:8000;
        server servidor3:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://servidores;
        }
    }
}
